import string
import os
import uuid
import sqlite3
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from dotenv import load_dotenv
from groq import Groq
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

# Load environment variables
load_dotenv()

app = Flask(__name__)
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=["200 per day", "50 per hour"],
    storage_uri="memory://"
)
# Initialize Groq client
# It will automatically look for the GROQ_API_KEY in your environment
groq_client = Groq()

# --- DATABASE SETUP ---
DB_FILE = "audit_log.db"

def init_db():
    """Initializes the SQLite database for the audit log."""
    with sqlite3.connect(DB_FILE) as conn:
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS audit_log (
                content_id TEXT PRIMARY KEY,
                creator_id TEXT,
                timestamp TEXT,
                attribution TEXT,
                confidence REAL,
                groq_score REAL,
                ttr_score REAL,
                status TEXT,
                appeal_reasoning TEXT
            )
        ''')
        conn.commit()

init_db()

# --- SIGNAL 1: GROQ LLM ---
def analyze_with_groq(text: str) -> float:
    """
    Sends the text to Llama-3 via Groq to assess semantic and stylistic coherence.
    Returns a float between 0.0 (Likely Human) and 1.0 (Likely AI).
    """
    prompt = f"""
    You are an expert stylometric AI detector. Analyze the following text and determine if it reads as human-written or AI-generated.
    AI text often has perfectly balanced structures, highly predictable transitions, and lacks emotional quirks. 
    Human text often contains varied pacing, idiosyncrasies, and organic leaps in logic.
    
    Return your analysis strictly in JSON format with a single key "ai_probability" and a float value between 0.0 (Definitely Human) and 1.0 (Definitely AI).
    
    Text to analyze:
    "{text}"
    """
    
    try:
        response = groq_client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You output JSON only."},
                {"role": "user", "content": prompt}
            ],
            model="llama-3.3-70b-versatile",
            response_format={"type": "json_object"},
            temperature=0.0 # Keep it deterministic
        )
        
        result_json = json.loads(response.choices[0].message.content)
        # Default to 0.5 if the model returns something unexpected
        return float(result_json.get("ai_probability", 0.5))
        
    except Exception as e:
        print(f"Groq API Error: {e}")
        return 0.5 
# --- SIGNAL 2: STYLOMETRICS (TTR) ---
def calculate_ttr(text: str) -> float:
    """
    Calculates the Type-Token Ratio (vocabulary diversity).
    Returns a float between 0.0 and 1.0. Higher means more vocabulary diversity.
    """
    # Remove punctuation and lowercase the text
    translator = str.maketrans('', '', string.punctuation)
    clean_text = text.translate(translator).lower()
    
    tokens = clean_text.split()
    
    if not tokens:
        return 0.0 # Prevent division by zero on empty strings
        
    unique_words = set(tokens)
    return len(unique_words) / len(tokens)
# --- ROUTES ---
@app.route("/submit", methods=["POST"])
@limiter.limit("5 per minute") # Rate limiting specific to this endpoint
def submit_content():
    data = request.get_json()
    
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing 'text' or 'creator_id' in request body"}), 400
        
    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()
    
    groq_score = analyze_with_groq(text)
    ttr_score = calculate_ttr(text)
    inverted_ttr = 1.0 - ttr_score 
    
    final_confidence = (groq_score * 0.70) + (inverted_ttr * 0.30)
    
    if final_confidence >= 0.76:
        attribution = "likely_ai"
        label = "Likely AI-Generated. Our detection signals indicate with high confidence that this content was primarily generated by artificial intelligence. If you believe this is an error, please submit an appeal."
    elif final_confidence <= 0.35:
        attribution = "likely_human"
        label = "Likely Human. Our detection signals indicate with high confidence that this content is organically written."
    else:
        attribution = "uncertain"
        label = "Unclassified. This content exhibits mixed signals. Our system cannot definitively determine whether it was written by a human or generated by AI."

    with sqlite3.connect(DB_FILE) as conn:
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO audit_log (content_id, creator_id, timestamp, attribution, confidence, groq_score, ttr_score, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ''', (content_id, creator_id, timestamp, attribution, final_confidence, groq_score, ttr_score, "classified"))
        conn.commit()
        
    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": round(final_confidence, 2),
        "label": label
    }), 200

@app.route("/appeal", methods=["POST"])
def submit_appeal():
    data = request.get_json()
    
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing 'content_id' or 'creator_reasoning'"}), 400
        
    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]
    
    with sqlite3.connect(DB_FILE) as conn:
        cursor = conn.cursor()
        
        # Check if the content exists
        cursor.execute('SELECT status FROM audit_log WHERE content_id = ?', (content_id,))
        row = cursor.fetchone()
        
        if not row:
            return jsonify({"error": "content_id not found"}), 404
            
        # Update the database
        cursor.execute('''
            UPDATE audit_log 
            SET status = 'under_review', appeal_reasoning = ? 
            WHERE content_id = ?
        ''', (reasoning, content_id))
        conn.commit()
        
    return jsonify({
        "message": "Appeal submitted successfully. Status updated to under_review.",
        "content_id": content_id
    }), 200

@app.route("/log", methods=["GET"])
def get_log():
    """Returns the entire audit log as JSON."""
    with sqlite3.connect(DB_FILE) as conn:
        conn.row_factory = sqlite3.Row # This allows us to fetch rows as dictionaries
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM audit_log ORDER BY timestamp DESC')
        rows = cursor.fetchall()
        
    # Convert SQLite rows to a list of standard dictionaries
    entries = [dict(row) for row in rows]
    return jsonify({"entries": entries}), 200

if __name__ == "__main__":
    app.run(debug=True)